import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import { cn } from "@/lib/utils";
import QueryProvider from "@/utils/quey-provider";
import ReduxProvider from "@/utils/redux-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <QueryProvider>
                <body
                    className={cn(
                        inter.className,
                        "flex flex-col min-h-screen"
                    )}
                    suppressHydrationWarning={true}
                >
                    <ReduxProvider>
                        <Navbar />
                        <div className="container mx-auto flex-1 justify-between py-10  ">
                            {children}
                        </div>
                        <Footer />
                    </ReduxProvider>
                </body>
            </QueryProvider>
        </html>
    );
}
