import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import QueryProvider from "@/utils/quey-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const queryClient = {};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <QueryProvider>
                <UserProvider>
                    <body
                        className={cn(
                            inter.className,
                            "flex flex-col min-h-screen"
                        )}
                    >
                        <Navbar />
                        <div className="container mx-auto flex-1 py-10">
                            {children}
                        </div>
                        <Footer />
                    </body>
                </UserProvider>
            </QueryProvider>
        </html>
    );
}
